### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by mbn76** [drewm/textpattern-to-wordpress#5]
Rather new to this coding and trying to move an old site that I didn't design from txp to wp for that very reason...
I must be screwing up at a fundamental level because the file generates a webpage (***/textpattern-to-wordpress.phop) that's filled strictly with the code (minus the txpconfig data at the beginning). Any help would be greatly appreciated. Thanks.

**Comment by drewm** [comment]
I can't offer support for this, sorry.
